spring.application.name=sghss

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sghss
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=INFO

spring.docker.compose.enabled=false